[package]
name = "sepolrs"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@gmx.com>"]

[dependencies]
byteorder = "1"
clap = "2"
croaring = "^0.3.5"
itertools="^0.7.8"
bitflags="^1.0.4"
lazy_static = "1.2.0"